### ISSUE TITLE
Auth issues

### ISSUE THREAD

**Issue by Denyerec** [bohwaz/micro-gpodder-server#1]
Hey there, found this project because gpodder.net is always 500 offline and needed something small to sync podcasts, but I'm struggling with getting it up and running - first I had to tweak to test isset() on a GET var to avoid  Undefined array key "token", and now I am once again stuck.

I can access the server through the browser and login, but when attempting to login with the same credentials via antennapod I simply receive a "Wrong username/password" error in the app. Alas, nothing is revealed in the error log.

**Comment by Denyerec** [comment]
Hey there, no worries, I know how it goes with OSS projects! I can't run golang on my hosting at the moment, so I'll have to keep searching :/

**Comment by bohwaz** [comment]
Should work now.
