### ISSUE TITLE
Main page works, Login/Registration doesn't

### ISSUE THREAD

**Issue by Jon367** [bohwaz/micro-gpodder-server#11]
The main page looks really nice, but if I try to go to the login or the registration pages, I get a 404 not found.

It wasn't working before, or after I added a configuration file. But with the configuration file, I now have the debug log, but in it, there's nothing related. There's just some GET requests.

I'm running this simply in the /var/www/html, being served by Apache2. I then have php 8.1.2, with the packages libapache2-mod-php, and php-sqlite3, the latter to work with of course SQlite3 that I have.

I'm really grateful for any help, thanks. I don't know what the issue could be.
![Screenshot from 2024-01-02 19-17-07](https://github.com/bohwaz/micro-gpodder-server/assets/76491945/c16d1a9f-617d-4f8f-9be2-79f7eeb7cdd2)

**Comment by bohwaz** [comment]
Enable the provided htaccess file.

**Comment by daikema** [comment]
Will note that in my case, I had to rewrite the htaccess file, though think that this was due to me running things under Litespeed instead of Apache.  So for me this worked - not sure if this file would also work under Apache or not:
```
RedirectMatch 404 inc/.*
RedirectMatch 404 data/.*

#FallbackResource /index.php
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.php [L]
```

**Comment by bohwaz** [comment]
Yes the .htaccess is for Apache, as documented :)
