### ISSUE TITLE
Login + URL validation issues

### ISSUE THREAD

**Issue by daikema** [bohwaz/micro-gpodder-server#12]
So tried to get this working last night and think I eventually did.  Needed to make a few changes to the source to get it to work though which I think are likely related to recent refactoring.

1. Login wasn't working, telling me I was logged in but not giving a session cookie.  The issue appeared related to [this line](https://github.com/bohwaz/micro-gpodder-server/blob/4b4d4a7a3eea4b27571dddc418772923b19f2afe/server/inc/API.php#L129) where this `error` function call seemed to be triggering an early end to processing.  Just commented the line out and that got me a different error message.

2. Then I was hitting an invalid username error.  The culprit seemed to be [this line](https://github.com/bohwaz/micro-gpodder-server/blob/4b4d4a7a3eea4b27571dddc418772923b19f2afe/server/inc/API.php#L135) which I also just commented out.  (The line following it also appears problematic, though harmless in its case).  That seemed to work as I wasn't using the "passwordless" version of the username with a couple of extra `__` and a token following it.  Based on my reading of [the docs](https://www.php.net/manual/en/function.strtok.php), though, I don't think replacing that (and the surrounding lines) with `$login = strtok($_SERVER['PHP_AUTH_USER'], '__');` would have quite the desired effect though as I think it wouldn't handle usernames with a single `_` well.

After making those two changes I was then able to login.

I then hit a URL validation error triggered by [this line](https://github.com/bohwaz/micro-gpodder-server/blob/4b4d4a7a3eea4b27571dddc418772923b19f2afe/server/inc/API.php#L87).  Basically it requires the url end with a `/` which wasn't the case for me.  For now I just removed the final `/` from the regex.  Following these three changes I was then able to login.

(Could pull request some of the above, but since these all appear to be related to recent changes to the codebase and I'm not sure if work is actively continuing there I figured I'd initially file these as an issue.  Similarly, as mentioned I haven't touched PHP code in ages).

**Comment by bohwaz** [comment]
1. should be fixed, thanks.
2. fixed too
3. no this regexp doesn't expect a URL finishing with a slash, but a hostname, following a slash and then following anything. So it should always work.

**Comment by bohwaz** [comment]
Yes I know, but then it means the URL is not valid if it does not include a path, so it's correct.

What I meant is that these are valid URLs:

```
https://foo.com/
https://foo.com/stream
```

But this is not:

```
https://foo.com
```

I don't see how your podcast feed URL could have an no path at all?

**Comment by daikema** [comment]
Just `curl -i -s https://listen.thevalmy.com` and you'll see an RSS feed.

**Comment by bohwaz** [comment]
Hum curl is actually automatically correcting to add the `/`, confirming that this is indeed an invalid url :)

Not sure what to do here.

**Comment by daikema** [comment]
If you're not verifying that, e.g. the TLD exists, a permissive approach seems to be pretty reasonable.

Would seem a bit odd to block something like http://example.com when you'll find that [in a related IETF RFC](https://datatracker.ietf.org/doc/html/rfc3986/#section-6.2.3) as an equivalent to http://example.com/, even if there is a prefered way you'd rather write it.

**Comment by bohwaz** [comment]
Alright, done :)
