### ISSUE TITLE
Publish a pre-built docker image

### ISSUE THREAD

**Issue by PHLAK** [bohwaz/micro-gpodder-server#13]
It would be nice if you published an official pre-built Docker image on [Docker Hub](https://hub.docker.com/) or [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) so we could easily pull down the image and updates via `docker pull`.

**Comment by bohwaz** [comment]
I don't use Docker myself nor Github, so feel free to publish whatever you want :)

**Comment by hnz101** [comment]
You could just replace the build context in your docker-compose file with this repo here, then you could also simple pull and get updates.
context: github.com/bohwaz/micro-gpodder-server#main

**Comment by PHLAK** [comment]
Thanks, I'm aware of the options I have. Was just politely requesting an official image be pushed.

**Comment by nwithan8** [comment]
Seems there's a few Docker Hub contributors keeping unofficial images in sync with the releases: https://hub.docker.com/search?q=opodsync

**Comment by bohwaz** [comment]
> Seems there's a few Docker Hub contributors keeping unofficial images in sync with the releases: https://hub.docker.com/search?q=opodsync

Thanks, I have removed docker files from this repo, and updated the readme to point to this URL, as I think it's better to delegate the management of docker distribution to the community.
