### ISSUE TITLE
Login and Register buttons return to index.php unless server is in the document root

### ISSUE THREAD

**Issue by djmandell** [bohwaz/micro-gpodder-server#16]
Hi there,

I've been trying to set up the server and have hit a weird problem that may be a bug or may be a configuration issue.  I originally tried to install the server in a subfolder under my document root (https://example.com/micro-gpodder), and found that while I could load index.php, if I clicked on either the Login or Register buttons the page would just reload, as if I'd done nothing.  I've got the .htaccess file in place and confirmed that it's doing its job (tried https://example.com/micro-gpodder/garbage and confirmed that I got index.php).

On a lark I tried creating a subdomain specifically for the service (http://micro.example.com) where the server would be directly in the document root of the site, and the document root was the same folder I'm using above (micro-gpodder).  When I do that, I click on Register and Login and see the appropriate pages.

I set up debugging in the app, and I see get requests when connecting via both methods.  In the case where I use micro.example.com/register I see:

2024-01-19 18:29:46 Got a GET request on register

In the case where I try to connect to example.com/micro-gpodder/register I see

2024-01-19 18:29:54 Got a GET request on micro-gpodder/register

I'm not really sure where to go from here, other than to ask: does the server have to be in the document root of the site in order to function?  Or is there something obvious that I'm missing?  

I'm more than happy to provide additional information to help resolve the problem.  I'd really rather have this service be in a subfolder rather than its own site if at all possible.

**Comment by bohwaz** [comment]
Installation in a subdirectory was not supported. I just fixed it, try new release :)
