### ISSUE TITLE
Running on a Raspberry Pi Zero

### ISSUE THREAD

**Issue by tuxcomputers** [bohwaz/micro-gpodder-server#22]
I have got this running on a Raspberry Pi Zero and I see the home screen, however if I click the register or the login all I get is a 404 not found page.

The versions I have installed
1. PHP: 7.4.33
2. Apache: 2.4.56
3. SQLite: 3.34.1

![image](https://github.com/bohwaz/micro-gpodder-server/assets/26516524/70d0881c-a949-4db9-8d22-046fbc947997)

**Comment by tuxcomputers** [comment]
Thinking it might be because I was using an IP instead of a hostname I added my pizero to the hosts file, still get 404

**Comment by tuxcomputers** [comment]
I enabled https on Apache and it started working fine, maybe add that to the README

**Comment by tuxcomputers** [comment]
I used a self signed certificate to enable https, now how do I configure AntennaPod to get past that fact?

**Comment by bohwaz** [comment]
https is not required, it will work without https, so it was probably a configuration issue on your side.

As for AntennaPod, this is not the AntennaPod forum.
