### ISSUE TITLE
Unique index on subscription_url?

### ISSUE THREAD

**Issue by tuxcomputers** [bohwaz/micro-gpodder-server#24]
`CREATE UNIQUE INDEX subscription_url ON subscriptions (url);`

This means that two different users would not be able to subscribe to the same podcast, would it not?

`CREATE UNIQUE INDEX subscription_url ON subscriptions (url, user);`

This would make it so the same user could have the same URL but a different user could.

Same issue with the devices index
`CREATE UNIQUE INDEX deviceid ON devices (deviceid);`

**Comment by bohwaz** [comment]
Good catch, fixed, thank you!
