### ISSUE TITLE
Synching a second AntennaPod device deletes all actions from all subscriptions

### ISSUE THREAD

**Issue by rhuneai** [bohwaz/micro-gpodder-server#29]
Hi bohwaz, I have setup micro-gpodder-server on docker and am trying to sync my old phone's AntennaPod to my new phone's AntennaPod. But when I sync the second phone play history is not synched and all the play actions are removed from micro-gpodder-server.

Steps to reproduce:

1. Delete data.sqlite and recreate container.
1. Create account from web interface.
2. Sign in from old phone, create new device (Pixel 3a).
3. Wait for successful sync from old phone.
4. Log out of sync on old phone (I am only doing this to try and prevent anything wiping history on the old phone).
5. Sign in from new phone, create new device (Pixel 8 Pro).
6. Wait for successful sync to new phone.
7. At this point podcasts have synced but no play history. Checking the web interface all play actions are now gone.

Here is the debug log from doing the above steps:
[Debug-SyncTwoPhones.txt](https://github.com/bohwaz/micro-gpodder-server/files/14866181/Debug-SyncTwoPhones.txt)

**Comment by rhuneai** [comment]
The first time I tried they had the same name, which I thought might have been the problem. I tried with different names the second time and it still occured. I was going to try and do some more testing and dig into the code, but haven't had a chance yet 😅

**Comment by bohwaz** [comment]
I changed the device creation logic, check with 0.3.0 tag if it works better?

**Comment by rhuneai** [comment]
Thanks for the update. Unfortunately I am running into issue # 33 as well, so can't test this yet.

**Comment by bohwaz** [comment]
Should be good now :)

**Comment by rhuneai** [comment]
An exception is thrown when creating the first device. At a guess, it looks like the 'data' column might have been renamed to 'json', but the SQL Script still creates it as 'data' (or the device function is using json instead of data column)?

```
[03-May-2024 12:09:22 UTC] ErrorException: SQLite3::prepare(): Unable to prepare statement: table devices has no column named json in /var/www/server/inc/DB.php:55
Stack trace:
#0 [internal function]: {closure}()
#1 /var/www/server/inc/DB.php(55): SQLite3->prepare()
#2 /var/www/server/inc/DB.php(81): DB->prepare2()
#3 /var/www/server/inc/DB.php(47): DB->simple()
#4 /var/www/server/inc/API.php(431): DB->upsert()
#5 /var/www/server/inc/API.php(228): API->devices()
#6 /var/www/server/inc/API.php(381): API->route()
#7 /var/www/server/index.php(81): API->handleRequest()
#8 {main}
```
```
[0] => INSERT INTO devices (deviceid, json, name, user) VALUES (:deviceid, :json, :name, :user) ON CONFLICT (deviceid, user) DO UPDATE SET deviceid = :deviceid, json = :json, name = :name, user = :user;
[1] => Array
	(
		[deviceid] => antennapod_on_pixel_3a
		[json] => {"caption":"AntennaPod on Pixel 3a","type":"mobile","subscriptions":0}
		[name] => AntennaPod on Pixel 3a
		[user] => 1
	)

```

**Comment by bohwaz** [comment]
Forgot one line from the PR, thanks :)

**Comment by rhuneai** [comment]
Works perfectly now, thanks! :)

Something strange I've noticed is that some of my subscriptions don't load properly on first synch to AntennaPod on a new device. Out of the 4 I have below, only In Machines We Trust shows up as the actual podcast. The others are shown as 'Unknown podcast'.
- feeds.npr.org/510289/podcast.xml
- feeds.megaphone.fm/hackedpodcast
- feeds.megaphone.fm/darknetdiaries
- feeds.megaphone.fm/inmachineswetrust

In order for them to be detected properly, I can open each one and refresh (pull down gesture) which shows the correct podcast details and loads all the episodes. At this point the play actions haven't been synched (only for the Unknown ones), but forcing a full synch then pulls them across.

I haven't found anything common between the ones that don't work straight away so have no idea why yet.
I imagine this is an AntennaPod issue, not a micro-gpodder-server thing.

If you want to investigate it anyway, let me know and I can open another issue.
