### ISSUE TITLE
Friendly title for subscriptions

### ISSUE THREAD

**Issue by tuxcomputers** [bohwaz/micro-gpodder-server#32]
Would it be possible that when a subscription is added that this app downloads the RSS file and parses it for the <title> and uses that as the friendly name for the subscription?

![image](https://github.com/bohwaz/micro-gpodder-server/assets/26516524/32401055-aa5f-4192-bed1-da07b4c51035)

**Comment by tuxcomputers** [comment]
![image](https://github.com/bohwaz/micro-gpodder-server/assets/26516524/7c5d99b5-4ae5-46ed-8a9d-c05e3fc55d75)

**Comment by bohwaz** [comment]
The clients don't provide this information AFAIK so it's not possible. If they do, please provide a patch.

**Comment by bohwaz** [comment]
Seemed useful after thinking about it, implemented.
