### ISSUE TITLE
Cannot create sync with AntennaPod

### ISSUE THREAD

**Issue by smoothml** [bohwaz/micro-gpodder-server#36]
Hello. I am having trouble setting up a sync with AntennaPod on my Android device. I have configured my server in a Docker container as per the project `README` and am hosting through a Cloudflare tunnel. I'm using the latest commit on `main` (v0.3.2). I can access the web UI without any problems and have setup a user account. When going through the setup on AntennaPod (the gpodder.net setup route) I get the error `Unable to connect to Gpodder.net (code 400: bad request)` as shown below.

![signal-2024-05-05-093021_002](https://github.com/bohwaz/micro-gpodder-server/assets/12639946/1c812f27-7009-4a22-a32f-ed97be4531e4)

When I click login is see the following logs:

```
gpodder-server  | [8] [Sun May  5 08:30:47 2024] Failed to poll event
gpodder-server  | [1] [Sun May  5 08:30:47 2024] 172.23.0.1:51442 Accepted
gpodder-server  | [1] [Sun May  5 08:30:47 2024] 172.23.0.1:51442 Closing
```

On v0.3.1 I found a different issue. I received the error `Gpodder.net is currently unavailable (code 500)` which clicking "Create device".

![signal-2024-05-03-193054](https://github.com/bohwaz/micro-gpodder-server/assets/12639946/28b9d0b3-d7d9-41b4-a4f5-cc178dda8518)

On this version, when logging in I saw the following server logs:

```
gpodder-server  | [1] [Sun May  5 08:22:32 2024] 172.19.0.1:47430 Accepted
gpodder-server  | [1] [Sun May  5 08:22:32 2024] 172.19.0.1:47430 Closing
gpodder-server  | [7] [Sun May  5 08:22:32 2024] Failed to poll event
gpodder-server  | [1] [Sun May  5 08:22:32 2024] Failed to poll event
gpodder-server  | [8] [Sun May  5 08:22:32 2024] 172.19.0.1:47432 Accepted
gpodder-server  | [8] [Sun May  5 08:22:32 2024] 172.19.0.1:47432 Closing
```

Then, when clicking "Create device" I saw:

```
gpodder-server  | [7] [Sun May  5 08:22:55 2024] Failed to poll event
gpodder-server  | [1] [Sun May  5 08:22:55 2024] 172.19.0.1:53846 Accepted
gpodder-server  | [8] [Sun May  5 08:22:55 2024] Failed to poll event
gpodder-server  | [1] [Sun May  5 08:22:55 2024] 172.19.0.1:53846 Closing
```

The following stacktrace appears in the `error.log`:

```
[05-May-2024 08:22:55 UTC] ErrorException: SQLite3::prepare(): Unable to prepare statement: table devices has no column named json in /var/www/server/inc/DB.php:55
Stack trace:
#0 [internal function]: {closure}()
#1 /var/www/server/inc/DB.php(55): SQLite3->prepare()
#2 /var/www/server/inc/DB.php(81): DB->prepare2()
#3 /var/www/server/inc/DB.php(47): DB->simple()
#4 /var/www/server/inc/API.php(431): DB->upsert()
#5 /var/www/server/inc/API.php(228): API->devices()
#6 /var/www/server/inc/API.php(381): API->route()
#7 /var/www/server/index.php(81): API->handleRequest()
#8 {main}
```

Any ideas what might be causing this? Thanks in advance 😄

**Comment by bohwaz** [comment]
Please update to last version, this should be fixed. If you have any other issue, enable debug log.
